### ISSUE TITLE
Already in Flathub

### ISSUE THREAD

**Issue by sabriunal** [flathub/io.gitlab.news_flash.NewsFlash#1]
Hi, 

FlashNews was already in Flathub (https://flathub.org/apps/com.gitlab.newsflash)

It seems that you created another Flatpak package for the same one (https://flathub.org/apps/io.gitlab.news_flash.NewsFlash)

**Comment by jangernert** [comment]
the plan is to end-of-life the old package

as you can see the old package is version 2.3.0 and the new one 2.3.1 with the only change being the app-id

**Comment by sabriunal** [comment]
Thanks for correcting me.
