### ISSUE TITLE
Why does NewsFlash need access to pulseaudio devices/microphones?

### ISSUE THREAD

**Issue by kekkoudesu** [flathub/io.gitlab.news_flash.NewsFlash#19]
The GNOME Software page for NewsFlash has this warning:

![image](https://github.com/flathub/io.gitlab.news_flash.NewsFlash/assets/88186997/9ca5f7f7-9a45-4c62-8d4c-13d0574d7f44)

This is the line that enables that permission: https://github.com/flathub/io.gitlab.news_flash.NewsFlash/blob/master/io.gitlab.news_flash.NewsFlash.json#L15

Why does NewsFlash need that permission?

**Comment by jangernert** [comment]
It doesn't use microphones as far as I know. Audio output is needed for things like embedded video/audio in articles.

**Comment by kekkoudesu** [comment]
I thought so. According to [this issue for GNOME Software](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2394), the pulseaudio socket lets applications access both input and output, but I guess because users are primarily concerned about microphone access, that's all the warning talks about.

> As mentioned the device scope is suggesting a bigger security hole, then pulseaudio access (listening to all mics, playing music) is in my understanding.

I guess they didn't get that far on Flathub (ongoing issue), which is why this warning doesn't display on Flathub for pulseaudio but does for pipewire permission: https://github.com/flathub-infra/website/issues/1919
