### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by maiido** [flathub/io.gitlab.news_flash.NewsFlash#23]
The zoom does not change

![image](https://github.com/user-attachments/assets/979c8d05-92b3-4757-a557-2f875f355e3a)

![image](https://github.com/user-attachments/assets/351f5574-5861-4d9e-9634-0fd238c0b29c)

I use Manjaro, Kde, Wayland

**Comment by ktbloomq** [comment]
Can confirm. This is a Flatpak specific issue. I use EndeavourOS, KDE, Wayland

**Comment by nirik** [comment]
Yeah, seeing it here also on kde in fedora rawhide. gnome is fine, but with kde the article print is super tiny and zoom doesn't work. ;( 
Newsfl… …_flash.NewsFlash 3.3.5                    stable      flathub       system

**Comment by maiido** [comment]
I received flat dependencies update today. No more issue
